name: blog-api

services:
  postgres:
    image: postgres:14.5
    container_name: blog-api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog-api
    volumes:
      - postgres-data:/data
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
