name: blog-api
version: 0.1.0.0
github: "unicolas/blog-api"
license: BSD3
author: "Nicolás Urquiola"
maintainer: "nicourquiola@gmail.com"
copyright: "2022 Nicolás Urquiola"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/unicolas/blog-api#readme>

language: GHC2021

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - base64
  - bytestring
  - dotenv
  - exceptions
  - fast-logger
  - hedis
  - jose
  - lens
  - mtl
  - password
  - postgresql-simple
  - resource-pool
  - servant
  - servant-client
  - servant-server
  - text
  - time
  - uuid
  - wai
  - warp

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  blog-api-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - blog-api

tests:
  blog-api-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - blog-api
      - containers
      - hspec
      - QuickCheck
      - quickcheck-instances
    build-tools:
      - hspec-discover:hspec-discover
