name: Haskell CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.0.2"
          enable-stack: true
          stack-version: "2.9.1"

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            .stack-work/
            ~/.stack/
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('blog-api.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('blog-api.cabal') }}
            ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-

      - name: Build
        run: stack build --fast

      - name: Run tests
        run: stack test
